import type { CSSProperties } from "react";

export const colors = {
  bg: "var(--vscode-editor-background)",
  fg: "var(--vscode-foreground)",
  border: "var(--vscode-panel-border, var(--vscode-editorWidget-border, #444))",
  btnBg: "var(--vscode-button-background)",
  btnFg: "var(--vscode-button-foreground)",
  btnHover: "var(--vscode-button-hoverBackground)",
  inputBg: "var(--vscode-input-background)",
  inputFg: "var(--vscode-input-foreground)",
  inputBorder: "var(--vscode-input-border, transparent)",
  errorFg: "var(--vscode-errorForeground, #e06c75)",
  badgeBg: "var(--vscode-badge-background)",
  badgeFg: "var(--vscode-badge-foreground)",
  descFg: "var(--vscode-descriptionForeground)",
};

export const s: Record<string, CSSProperties> = {
  app: {
    display: "flex",
    flexDirection: "row",
    height: "100vh",
    color: colors.fg,
    background: colors.bg,
    fontFamily: "var(--vscode-font-family)",
    fontSize: "var(--vscode-font-size, 13px)",
  },
  pane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    padding: 12,
    overflow: "auto",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    fontWeight: 600,
    marginBottom: 8,
  },
  headerTitle: {
    fontWeight: 600,
  },
  headerToggles: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
    fontWeight: 400,
    fontSize: "0.9em",
  },
  toggleLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    cursor: "pointer",
  },
  row: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: "6px 4px",
    borderRadius: 3,
    borderBottom: `1px solid ${colors.border}`,
  },
  rowPending: {
    opacity: 0.6,
  },
  handle: {
    cursor: "grab",
    userSelect: "none",
    padding: "0 4px",
  },
  name: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  input: {
    background: colors.inputBg,
    color: colors.inputFg,
    border: `1px solid ${colors.inputBorder}`,
    padding: "2px 6px",
    flex: 1,
    minWidth: 0,
  },
  button: {
    background: colors.btnBg,
    color: colors.btnFg,
    border: "none",
    padding: "0 8px",
    cursor: "pointer",
    borderRadius: 2,
    height: 24,
    lineHeight: "24px",
    display: "inline-flex",
    alignItems: "center",
    fontSize: "inherit",
  },
  buttonGhost: {
    background: "transparent",
    color: colors.fg,
    border: `1px solid ${colors.border}`,
    padding: "0 8px",
    cursor: "pointer",
    borderRadius: 2,
    height: 24,
    lineHeight: "24px",
    display: "inline-flex",
    alignItems: "center",
    fontSize: "inherit",
  },
  rowRemoved: {
    opacity: 0.6,
  },
  badge: {
    background: colors.badgeBg,
    color: colors.badgeFg,
    padding: "1px 6px",
    borderRadius: 8,
    fontSize: "0.85em",
  },
  error: {
    color: colors.errorFg,
    padding: 6,
    fontSize: "0.9em",
  },
  addRow: {
    display: "flex",
    flexDirection: "row",
    gap: 6,
    marginTop: 12,
  },
  desc: {
    color: colors.descFg,
    fontSize: "0.85em",
  },
};
