import type { CSSProperties } from "react";

export const colors = {
  bg: "var(--vscode-editor-background)",
  fg: "var(--vscode-foreground)",
  border: "var(--vscode-panel-border, var(--vscode-editorWidget-border, #444))",
  btnBg: "var(--vscode-button-background)",
  btnFg: "var(--vscode-button-foreground)",
  btnHover: "var(--vscode-button-hoverBackground)",
  inputBg: "var(--vscode-input-background)",
  inputFg: "var(--vscode-input-foreground)",
  inputBorder: "var(--vscode-input-border, transparent)",
  errorFg: "var(--vscode-errorForeground, #e06c75)",
  badgeBg: "var(--vscode-badge-background)",
  badgeFg: "var(--vscode-badge-foreground)",
  descFg: "var(--vscode-descriptionForeground)",
};

export const s: Record<string, CSSProperties> = {
  app: {
    display: "flex",
    flexDirection: "row",
    height: "100vh",
    color: colors.fg,
    background: colors.bg,
    fontFamily: "var(--vscode-font-family)",
    fontSize: "var(--vscode-font-size, 13px)",
  },
  pane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    padding: 12,
    overflow: "auto",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    fontWeight: 600,
    marginBottom: 8,
  },
  headerTitle: {
    fontWeight: 600,
  },
  row: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: "6px 4px",
    borderRadius: 3,
    borderBottom: `1px solid ${colors.border}`,
  },
  rowPending: {
    opacity: 0.6,
  },
  handle: {
    cursor: "grab",
    userSelect: "none",
    padding: "0 4px",
    width: 18,
    boxSizing: "border-box",
    textAlign: "center",
  },
  name: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  input: {
    background: colors.inputBg,
    color: colors.inputFg,
    border: `1px solid ${colors.inputBorder}`,
    padding: "2px 6px",
    flex: 1,
    minWidth: 0,
  },
  button: {
    background: colors.btnBg,
    color: colors.btnFg,
    border: "none",
    padding: "0 8px",
    cursor: "pointer",
    borderRadius: 2,
    height: 24,
    lineHeight: "24px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "inherit",
    minWidth: 90,
    boxSizing: "border-box",
  },
  buttonGhost: {
    background: "transparent",
    color: colors.fg,
    border: `1px solid ${colors.border}`,
    padding: "0 8px",
    cursor: "pointer",
    borderRadius: 2,
    height: 24,
    lineHeight: "24px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "inherit",
    minWidth: 90,
    boxSizing: "border-box",
  },
  buttonGhostSmall: {
    background: "transparent",
    color: colors.fg,
    border: `1px solid ${colors.border}`,
    padding: "0 6px",
    cursor: "pointer",
    borderRadius: 2,
    height: 22,
    lineHeight: "22px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.9em",
    minWidth: 54,
    boxSizing: "border-box",
  },
  rowRemoved: {
    opacity: 0.6,
  },
  badge: {
    background: colors.badgeBg,
    color: colors.badgeFg,
    padding: "1px 6px",
    borderRadius: 8,
    fontSize: "0.85em",
    minWidth: 64,
    textAlign: "center",
    display: "inline-block",
    boxSizing: "border-box",
  },
  badgeActive: {
    background: "var(--vscode-debugIcon-startForeground, #89d185)",
    color: "var(--vscode-editor-background, #1e1e1e)",
    padding: "1px 6px",
    borderRadius: 8,
    fontSize: "0.85em",
    fontWeight: 600,
    minWidth: 64,
    textAlign: "center",
    display: "inline-block",
    boxSizing: "border-box",
  },
  error: {
    color: colors.errorFg,
    padding: 6,
    fontSize: "0.9em",
  },
  addRow: {
    display: "flex",
    flexDirection: "row",
    gap: 6,
    marginTop: 12,
  },
  desc: {
    color: colors.descFg,
    fontSize: "0.85em",
  },
  badgeButton: {
    background: colors.badgeBg,
    color: colors.badgeFg,
    padding: "1px 6px",
    borderRadius: 8,
    fontSize: "0.85em",
    minWidth: 64,
    textAlign: "center" as const,
    display: "inline-flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 4,
    boxSizing: "border-box" as const,
    border: "none",
    cursor: "pointer",
  },
  statusChevron: {
    width: 7,
    height: 7,
    borderRight: "2px solid currentColor",
    borderBottom: "2px solid currentColor",
    opacity: 0.82,
    transform: "translateY(-2px) rotate(45deg)",
    flex: "0 0 auto",
  },
  badgeButtonActive: {
    background: "var(--vscode-debugIcon-startForeground, #89d185)",
    color: "var(--vscode-editor-background, #1e1e1e)",
    padding: "1px 6px",
    borderRadius: 8,
    fontSize: "0.85em",
    fontWeight: 600,
    minWidth: 64,
    textAlign: "center" as const,
    display: "inline-flex",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: 4,
    boxSizing: "border-box" as const,
    border: "none",
    cursor: "pointer",
  },
  statusMenu: {
    position: "absolute" as const,
    top: "100%",
    left: 0,
    zIndex: 10,
    background:
      "var(--vscode-menu-background, var(--vscode-editor-background))",
    border: `1px solid var(--vscode-menu-border, ${colors.border})`,
    borderRadius: 4,
    padding: "4px 0",
    minWidth: 120,
    boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
  },
  statusMenuItem: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "4px 12px",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    color: "inherit",
    width: "100%",
    textAlign: "left" as const,
    fontSize: "inherit",
  },
  statusMenuItemActive: {
    fontWeight: 600,
  },
  groupHeader: {
    display: "flex",
    alignItems: "center" as const,
    gap: 6,
    padding: "6px 4px",
    cursor: "pointer",
    userSelect: "none" as const,
    fontWeight: 600,
    fontSize: "0.9em",
    color: colors.fg,
    background: "transparent",
    border: "none",
    width: "100%",
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.border}`,
  },
  groupHeaderDisabled: {
    display: "flex",
    alignItems: "center" as const,
    gap: 6,
    padding: "6px 4px",
    userSelect: "none" as const,
    fontWeight: 600,
    fontSize: "0.9em",
    color: colors.descFg,
    opacity: 0.5,
    background: "transparent",
    border: "none",
    width: "100%",
    textAlign: "left" as const,
    borderBottom: `1px solid ${colors.border}`,
  },
  handleHidden: {
    visibility: "hidden" as const,
    padding: "0 4px",
    width: 18,
    boxSizing: "border-box",
    textAlign: "center",
  },
  taskStateIcon: {
    width: 18,
    padding: "0 4px",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none" as const,
    fontSize: "0.9em",
    lineHeight: 1,
  },
  taskStateIconActive: {
    color: "var(--vscode-debugIcon-startForeground, #89d185)",
  },
  taskStateIconCompleted: {
    color: "var(--vscode-testing-iconPassed, #73c991)",
  },
  taskList: {
    marginLeft: 18,
    borderLeft: `1px solid ${colors.border}`,
  },
  taskRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: "4px 4px 4px 8px",
    borderBottom: `1px solid ${colors.border}`,
  },
  taskStatusMenuAnchor: {
    position: "relative",
    display: "inline-block",
  },
  taskStatusButton: {
    minWidth: 84,
    height: 26,
    padding: "0 8px 0 10px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderRadius: 4,
    background: "transparent",
    color: colors.fg,
    fontSize: "0.9em",
    fontFamily: "inherit",
    cursor: "pointer",
    boxSizing: "border-box",
    whiteSpace: "nowrap",
  },
  taskStatusButtonActive: {
    borderColor: "rgba(137, 209, 133, 0.48)",
    color: "var(--vscode-debugIcon-startForeground, #89d185)",
  },
  taskStatusButtonQueued: {
    color: colors.descFg,
  },
  taskStatusButtonSkipped: {
    color: colors.descFg,
    opacity: 0.78,
  },
  taskStatusButtonDisabled: {
    opacity: 0.55,
    cursor: "default",
  },
  taskEmpty: {
    marginLeft: 18,
    padding: "4px 4px 4px 8px",
    color: colors.descFg,
    fontSize: "0.9em",
  },
};
